### PR TITLE
fix: support strict type

### PR DESCRIPTION
**Pull request by danzrou**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #26 

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by NetanelBasal** [comment]
@danzrou tests are failing.

**Comment by danzrou** [comment]
updated

**Comment by NetanelBasal** [comment]
@danzrou the change breaks many things in our code.

**Comment by danzrou** [comment]
Redundant after latest type changes

**Pull request closed without merging**
