### PR TITLE
Feature/patchEnable & patchDisable new Control Methods implementation and documentation

### PR DESCRIPTION
**Pull request by KamilSocha91**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ x ] The commit message follows our guidelines: CONTRIBUTING.md#commit
- [ x ] Tests for the changes have been added (for bug fixes / features)
- [ x ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ x ] Bugfix
[ x ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ x ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Current there is only method for single control enable/disable - setEnable()/setDisable().

Issue Number: https://github.com/ngneat/reactive-forms/issues/71

## What is the new behavior?

Two new Control Methods patchEnable() & patchDisable(). They base on setEnable(), setDisable() methods where new behavior is possibility to disable list of controls.

Idea behind this methods is base on patchValue() method.

This change would is completely new and behaves different base on form element use:

1.  formControl.ts:
- patchEnable(), works same as setEnable for code consistency
- patchDisable(), works same as setDisable for code consistency

2. formGroup.ts:
- patchEnable(), inputs object with control names which should be enabled and options
- patchDisable(), inputs object with control names which should be disabled and options

3. formArray.ts:
- patchEnable(), inputs boolean array where true enables control, false disable it
- patchDisable(), inputs boolean array where false enables control, true disable it

## Does this PR introduce a breaking change?

```
[ ] Yes
[ x ] No
```

This is new methods so it would not break already existing code.

## Other information

This is my first contribution for ngneat so I am welcome for critics :)

### CODE REVIEW

**Comment by NetanelBasal** [comment]
Thanks for the PR. I'm not sure if that's a common use case. @itayod @danzrou, what do u think?

**Comment by itayod** [comment]
> Thanks for the PR. I'm not sure if that's a common use case. @itayod @danzrou, what do u think?

I think we should simplify it, meaning for `FormControl` & `FormArray` it doesn't make a lot of sense, as for `FormGroup` we can use the old `setEnable` & `setDisable` methods and modify their signature to also accept an `Array`.

How is that sound to you?

**Comment by KamilSocha91** [comment]
@itayod 
> I think we should simplify it, meaning for `FormControl` & `FormArray` it doesn't make a lot of sense, as for `FormGroup` we can use the old `setEnable` & `setDisable` methods and modify their signature to also accept an `Array`.

That's true. Ive planned to implement it only for `FormGroup` but since `patchValue` is implemented for `FormControl` just for symmetry. I did the same for `patchDisable`.

```
 /**
   * Patches the value of a control.
   *
   * This function is functionally the same as {@link FormControl#setValue setValue} at this level.
   * It exists for symmetry with {@link FormGroup#patchValue patchValue} on `FormGroups` and
   * `FormArrays`, where it does behave differently.
   *
   * @see `setValue` for options
   */
  patchValue(value: any, options: {
    onlySelf?: boolean,
    emitEvent?: boolean,
    emitModelToViewChange?: boolean,
    emitViewToModelChange?: boolean
  } = {}): void {
    this.setValue(value, options);
  }
```

**Comment by KamilSocha91** [comment]
@NetanelBasal @itayod @danzrou 

So this issue is relevant or should not be implemented?

**Comment by NetanelBasal** [comment]
should not be implemented

**Pull request closed without merging**
