### PR TITLE
fix: allow NgAbstractControl as validator param

### PR DESCRIPTION
**Pull request by chrisguttandin**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: CONTRIBUTING.md#commit
- [-] Tests for the changes have been added (for bug fixes / features)
- [-] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

The latest version (v1.5) doesn't compile anymore with strict mode enabled.

Issue Number: N/A

## What is the new behavior?

It compiles again with the fix.

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

## Other information

Please let me know if there is anything I should change.

### CODE REVIEW

**Comment by itayod** [comment]
@chrisguttandin could you explain your use-case?

**Comment by chrisguttandin** [comment]
Hi @itayod, sorry I should have explained it better in the first place. I was the one who already created #26. The problem is that @ngneat/reactive-forms itself doesn't compile anymore when using TypeScript's (or Angular's) `--strict` flag.

I created a small repo to reproduce the error: https://github.com/chrisguttandin/reactive-forms-demo. Running `ng build` does currently fail since the `control` param of the validator functions is not assignable to the `control` param of the original validator functions.

**Comment by itayod** [comment]
Hi @chrisguttandin sorry for the delay, I am kind of busy these days...

Haven't look deeply at your problem, it seems like there are 2 ways we can fix this.
1. to add Angular's `AbstractControl` to the generic just like you suggested (would be the easier/faster solution, but not the correct one).
2. create a wrapper to Angular's validator just like we did with the rest of the objects, (this one is the right solution but requires more effort, considering that we will need to update also the schematics and the linter accordingly).

I will take a deeper look at it once I will have the time and let you know what we decide here.

**Comment by itayod** [comment]
@chrisguttandin thanks for bringing that up, it seems to be caused due to this [breaking-changes](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-0.html#breaking-changes) in typescript 4.

Thanks for taking the time and post this PR, good work 🙏

**Pull request merged**
